### ISSUE TITLE
Using localstorage or cookies to remember the user's settings.

### ISSUE THREAD

**Issue by nathan-a-macleod** [camilstaps/HebrewParseTrainer#3]
So I've been thinking of an idea for a new feature for ParseTrainer which would make it a bit more convenient & easier to use. Essentially, when you change the settings such as the following:
![Screenshot 2021-03-21 8 58 50 PM](https://user-images.githubusercontent.com/64553342/111922151-2d029600-8a90-11eb-9b1a-321eb7d88ff0.png)

It would be great if that would automatically save using something like LocalStorage or cookies so that when the page is refreshed, it won't remove the user's settings. I'm not entirely sure if that would be possible or how it would be done using PHP - but I think if it was implemented it would be very helpful.

**Comment by camilstaps** [comment]
Yes, good idea :thumbsup:

I don't have time to implement this myself but can review a pull request and update the website if you or somebody else does.

**Comment by nathan-a-macleod** [comment]
Yep, I could probably implement it using JavaScript. Unfortunately, I don't really have any experience using PHP, but I do know how to use JavaScript. It looks like in the `public/js` folder, JavaScript does most of the work - maybe I could add a new JavaScript file that does the following:
* checks if all the elements with the className of "form-group" have loaded
* adds a "change" event listener to all of them
* when this event listener is activated, it could save the settings to localstorage/cookies
* when the javascript file is run, it could restore the user's settings from localstorage/cookies

If I did that, I have a few questions relating more to the PHP side of things:

* would the javascript file be loaded whenever the page is refreshed?
* would it be possible to update the actual settings just using JavaScript?

**Comment by camilstaps** [comment]
Yes, you can do this fully in JavaScript. If you add your code to the large `$(document).ready` handler in hebrewparsetrainer.js it will be run on every page load.

In https://github.com/HebrewTools/ParseTrainer/blob/03f9b1c1e28049274304247d8717d2bfd8c024b5/public/js/hebrewparsetrainer.js#L153-L155 you can see how the settings are retrieved from the input fields. You can search a bit around for how to set the values of these input fields instead, e.g. https://stackoverflow.com/q/15044340.

The `change` listener you mention already exists: https://github.com/HebrewTools/ParseTrainer/blob/03f9b1c1e28049274304247d8717d2bfd8c024b5/public/js/hebrewparsetrainer.js#L349-L351
